spring:
  cloud:
    stream:
      function:
        definition: onCovid19RawData
      bindings:
        onCovid19RawData-in-0:
          destination: jhu/csse/covid19/raw
solace:
  java:
    host: 'tcp://localhost:55555'
    msgVpn: default
    clientUsername: default
    clientPassword: default
  jms:
    host: 'tcp://localhost:55555'
    msgVpn: default
    clientUsername: default
    clientPassword: default
logging:
  level:
    root: info
    org:
      springframework: info