spring:
  cloud:
    stream:
      function:
        definition: onCovidRawDataRegion
      bindings:
        onCovidRawDataRegion-in-0:
          destination: jhu/csse/covid19/raw
solace:
  java:
    host: ${host:tcp://localhost:55555}
    msgVpn: ${msgVpn:default}
    clientUsername: ${clientUsername:default}
    clientPassword: ${clientPassword:default}
  jms:
    host: ${host:tcp://localhost:55555}
    msgVpn: ${msgVpn:default}
    clientUsername: ${clientUsername:default}
    clientPassword: ${clientPassword:default}
logging:
  level:
    root: info
    org:
      springframework: info